name: CI

on:
  push:
    branches: [ master, trying, staging ]
  pull_request:
    branches: [ master, trying, staging ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  gdal_34:
    name: "ci gdal-34"
    runs-on: ubuntu-latest
    container:
      image: osgeo/gdal:ubuntu-small-3.4.0

    strategy:
      matrix:
        features: ["", "--all-features"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install build deps
        run: |
          apt-get update -y
          apt-get install build-essential -y
      - name: Setup building
        run: |
          export CC="clang-9"
          export CXX="clang++-9"
      - name: Check with Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Check with Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets ${{ matrix.features }} -- -D warnings
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.features }} --verbose
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.features }} --verbose
